INSERT INTO Constellation (abbreviation, name) VALUES ('and', 'Andromeda');
INSERT INTO Constellation (abbreviation, name) VALUES ('ant', 'Antlia');
INSERT INTO Constellation (abbreviation, name) VALUES ('aps', 'Apus');
INSERT INTO Constellation (abbreviation, name) VALUES ('aqr', 'Aquarius');
INSERT INTO Constellation (abbreviation, name) VALUES ('aql', 'Aquila');
INSERT INTO Constellation (abbreviation, name) VALUES ('ara', 'Ara');
INSERT INTO Constellation (abbreviation, name) VALUES ('ari', 'Aries');
INSERT INTO Constellation (abbreviation, name) VALUES ('aur', 'Auriga');
INSERT INTO Constellation (abbreviation, name) VALUES ('cnc', 'Cancer');
INSERT INTO Constellation (abbreviation, name) VALUES ('cma', 'Canis Major');
INSERT INTO Constellation (abbreviation, name) VALUES ('cap', 'Capricornus');
INSERT INTO Constellation (abbreviation, name) VALUES ('cas', 'Cassiopeia');
INSERT INTO Constellation (abbreviation, name) VALUES ('cru', 'Crux');
INSERT INTO Constellation (abbreviation, name) VALUES ('for', 'Fornax');
INSERT INTO Constellation (abbreviation, name) VALUES ('lib', 'Libra');
INSERT INTO Constellation (abbreviation, name) VALUES ('lyn', 'Lynx');


INSERT INTO Star (name, constellation_abbreviation) VALUES ('Sirrah', 'and');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Mirach', 'and');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Almach', 'and');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Sadalmelik', 'and');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Sadalsuud', 'aqr');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Sirius', 'cma');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Theta', 'cma');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Schedar', 'cas');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Achird', 'cas');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Acrux', 'cru');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Fornacis', 'for');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Beta Fornacis', 'for');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Zubeneschamali', 'lib');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Gliese', 'lib');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Pleione', 'ib');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Elvashak', 'lyn');
INSERT INTO Star (name, constellation_abbreviation) VALUES ('Alsciaukat', 'lyn');